package com.evrhel.bsp;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.*;

/**
 * Defines a structure containing <code>Polygon</code>s, a <code>BSPTree</code>, and
 * a bounding box wrapping the <code>Polygon</code>s.
 */
public class World {

    public static World worldFromFile(String filename) throws FileNotFoundException {
        List<String> lines = new LinkedList<>();
        Scanner fin = new Scanner(new FileInputStream(filename));
        while (fin.hasNextLine()) {
            String line = fin.nextLine().trim();
            if (line.length() > 0 && line.charAt(0) != '#')
                lines.add(line);
        }
        fin.close();

        List<Polygon> polys = new LinkedList<>();
        lines.forEach(line -> {
            String[] tokens = line.split(" ");
            float x0, y0, x1, y1;
            String name = null;

            if (tokens.length < 4) {
                System.out.printf("Malformed line: \"%s\"\n", line);
                return;
            }

            try {
                x0 = Float.parseFloat(tokens[0]);
                y0 = Float.parseFloat(tokens[1]);
                x1 = Float.parseFloat(tokens[2]);
                y1 = Float.parseFloat(tokens[3]);
            } catch (NumberFormatException e) {
                System.out.printf("Malformed line: \"%s\"\n", line);
                return;
            }

            if (tokens.length > 4)
                name = tokens[4];

            polys.add(new Polygon(name, new Vector2(x0, y0), new Vector2(x1, y1)));
        });

        return new World(polys);
    }

    private final List<Polygon> polys;
    private final BSPTree bspTree;
    private final Vector2 min, max;

    /**
     * Creates a new <code>World</code> from a <code>List</code> of <code>Polygon</code>s. A
     * <code>BSPTree</code> will also be generated for the <code>Polygon</code>s in this
     * <code>World</code>.
     *
     * @param polys A non-<code>null</code> <code>List</code> containing non-<code>null</code>
     *              <code>Polygon</code>s.
     */
    public World(List<Polygon> polys) {
        this.polys = new ArrayList<>(polys);

        // Determine the bounding box of the world
        this.min = Vector2.Inf();
        this.max = Vector2.NInf();
        polys.forEach(poly -> {
            Vector2 start = poly.getStart();
            Vector2 end = poly.getEnd();

            this.min.x = Math.min(this.min.x, start.x);
            this.min.x = Math.min(this.min.x, end.x);
            this.min.y = Math.min(this.min.y, start.y);
            this.min.y = Math.min(this.min.y, end.y);

            this.max.x = Math.max(this.max.x, start.x);
            this.max.x = Math.max(this.max.x, end.x);
            this.max.y = Math.max(this.max.y, start.y);
            this.max.y = Math.max(this.max.y, end.y);
        });

        this.bspTree = new BSPTree(this.polys);
    }

    /**
     * Returns an unmodifiable view of the raw <code>Polygon</code>s in this
     * <code>World</code>.
     *
     * @return The <code>Polygon</code>s.
     */
    public List<Polygon> getPolys() {
        return Collections.unmodifiableList(this.polys);
    }

    /**
     * Returns the <code>BSPTree</code> generated by this <code>World</code>.
     *
     * @return The <code>BSPTree</code>.
     */
    public BSPTree getBspTree() {
        return bspTree;
    }

    /**
     * Returns the minimum coordinates of the <code>World</code>'s bounding box.
     *
     * @return The minimum coordinates.
     */
    public Vector2 getMin() {
        return new Vector2(this.min);
    }

    /**
     * Returns the maximum coordinates of the <code>World</code>'s bounding box.
     *
     * @return The maximum coordinates.
     */
    public Vector2 getMax() {
        return new Vector2(this.max);
    }
}
